### ISSUE TITLE
Import screen issues

### ISSUE THREAD

**Issue by NicholasKatsambiris** [richtabor/MerlinWP#31]
Hey Rich, 

I was pulling my hair out trying to find out why the users and options section on the import always failed. I thought i was doing something wrong but then noticed the included york-pro demo theme. 

When i tested this on the york demo the same issue appeared. The users will never import and the options displays that it failed however it looks like all options were imported.

I'll keep testing however it looks like the user transient is never set so that function never executes, regarding the options i'm not sure what would be causing this. If you need anything else let me know.

**Comment by primozcigler** [comment]
Hey @NicholasKatsambiris,

The importer has been recently totally revamped and it's much more reliable now - more about it here: https://primoz.blog/pushing-merlin-wp-towards-stable-release/

I know it's been a while since you wrote here, but will you test the Merlin again and if the issue persists please reopen this issue, ok?
