### ISSUE TITLE
Add back the license step skip button, removed in PR #68

### ISSUE THREAD

**Issue by richtabor** [richtabor/MerlinWP#71]
Being able to skip any part of the wizard is pretty important for a user's control of the process. We don't want a situation where a user has to sit with their wizard half-done while they're locating licenses, trying to validate a key (if they've purchased from outside of EDD), or if they simply don't have one.

I vote we revert #68 and add the button back in. Maybe it could have a custom label string, for example "Add Later" instead of "Skip", but we really need to have a way for folks to continue with the setup process.

What do you think?

**Comment by capuderg** [comment]
Hmm, could we maybe add a flag for removing the skip button in the config file? By default, the skip button would be shown, but we could disable it with this flag in the config file?

**Comment by primozcigler** [comment]
I believe this needs some more explanation from our side. Our themes need to be activated prior importing the demo content. This way we fight against piracy of our products because for the OCDI we have things in control.

However, I agree with @richtabor that just because this is our decision, we should not change the default behavior of this open source project. If the Merlin was initially meant to be skippable in every step, this philosophy should be embraced and respected and treated as default. However, it's always nice to allow for configuration out of the box.

I suggest either adding the optional config flag for the steps to not be skippable (skippable by default). The other alternative is adding a hook (filter).

**Comment by richtabor** [comment]
That works! I'll submit a PR here shortly

**Comment by primozcigler** [comment]
:+1:
